"""empty message

Revision ID: 040b11a76b88
Revises: 58990ea71d97
Create Date: 2021-02-02 15:20:18.513160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040b11a76b88'
down_revision = '58990ea71d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'serial_keys', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'serial_keys', 'expert_advisors', ['ea_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serial_keys', type_='foreignkey')
    op.drop_constraint(None, 'serial_keys', type_='foreignkey')
    # ### end Alembic commands ###
