"""empty message

Revision ID: 58990ea71d97
Revises: 
Create Date: 2021-02-02 15:19:51.425640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58990ea71d97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=90), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=90), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('confirm_code', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serial_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_login', sa.Integer(), nullable=True),
    sa.Column('s_key', sa.String(length=90), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_login'),
    sa.UniqueConstraint('s_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serial_keys')
    op.drop_table('users')
    op.drop_table('expert_advisors')
    # ### end Alembic commands ###
