"""empty message

Revision ID: bbe9f6857aa4
Revises: 040b11a76b88
Create Date: 2021-02-03 13:22:02.321252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbe9f6857aa4'
down_revision = '040b11a76b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert_advisors', 'summary')
    op.create_foreign_key(None, 'serial_keys', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'serial_keys', 'expert_advisors', ['ea_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serial_keys', type_='foreignkey')
    op.drop_constraint(None, 'serial_keys', type_='foreignkey')
    op.add_column('expert_advisors', sa.Column('summary', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
